server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.18.154:8848
  application:
    name: gulimall-order
  datasource:
    username: xiaoma
    password: 555dedd+5
    url: jdbc:mysql://49.234.18.154:3306/gulimall_oms?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
